name: CI
on:
  push:

defaults:
  run:
    shell: bash -el {0}

jobs:
  tests:
    name: Tests - Python ${{ matrix.python-version }} - ${{ matrix.os }}
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.12']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        exclude:
          - os: windows-latest
            python-version: '2.7'
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          cache-environment: true
          create-args: pytest python=${{ matrix.python-version }}
      - name: Add micromamba to GITHUB_PATH
        run: echo "${HOME}/micromamba-bin" >> "$GITHUB_PATH"
      - run: pytest -v tests.py
